## Лабораторная работа №1
Зайцев Н.В. ПИ20-1В

In [1]:
import torch

In [11]:
# Задание 1
a = torch.tensor([[5.0,2.0],[7.0,5.0]])
b = torch.tensor([[1.0,4.0],[2.0,3.0]])

In [12]:
# Задание 2
a.add(b)

tensor([[6., 6.],
        [9., 8.]])

In [13]:
# Задание 3
a.sub(b)

tensor([[ 4., -2.],
        [ 5.,  2.]])

In [14]:
# Задание 4
a.mul(b)

tensor([[ 5.,  8.],
        [14., 15.]])

In [15]:
# Задание 5
a.div(b)

tensor([[5.0000, 0.5000],
        [3.5000, 1.6667]])

In [25]:
# Задание 6
print(a == b)

print(a > b)

print(a < b)

print(a != b)

print(a >= b)

print(a <= b)

tensor([[False, False],
        [False, False]])
tensor([[ True, False],
        [ True,  True]])
tensor([[False,  True],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[ True, False],
        [ True,  True]])
tensor([[False,  True],
        [False, False]])


In [26]:
# Задание 7
print(torch.sin(a))
print(torch.sin(b))

print(torch.cos(a))
print(torch.cos(b))

print(torch.exp(a))
print(torch.exp(b))

print(torch.log(a))
print(torch.log(b))

print(torch.abs(a))
print(torch.abs(b))

tensor([[-0.9589,  0.9093],
        [ 0.6570, -0.9589]])
tensor([[ 0.8415, -0.7568],
        [ 0.9093,  0.1411]])
tensor([[ 0.2837, -0.4161],
        [ 0.7539,  0.2837]])
tensor([[ 0.5403, -0.6536],
        [-0.4161, -0.9900]])
tensor([[ 148.4132,    7.3891],
        [1096.6332,  148.4132]])
tensor([[ 2.7183, 54.5981],
        [ 7.3891, 20.0855]])
tensor([[1.6094, 0.6931],
        [1.9459, 1.6094]])
tensor([[0.0000, 1.3863],
        [0.6931, 1.0986]])
tensor([[5., 2.],
        [7., 5.]])
tensor([[1., 4.],
        [2., 3.]])


In [28]:
# Задание 8
batch1 = torch.randn(3,1,5)
batch2 = torch.randn(3,2,4,8)

In [29]:
print(batch1)
print(batch2)

tensor([[[-0.4680,  1.1657, -0.6988, -1.0783, -0.5190]],

        [[ 1.1129, -0.2873,  0.4725,  0.7223,  1.6434]],

        [[-1.4992, -0.7216,  1.0614, -0.2172, -0.3948]]])
tensor([[[[ 0.0555,  0.4605, -0.1131,  0.8106,  0.3179, -0.7747,  0.1790,
            1.0387],
          [-1.5410,  1.0130,  0.2872, -1.1453, -1.4043, -0.4785, -1.0843,
            0.1859],
          [-0.9731, -0.5468,  2.0262,  1.4674,  0.2339,  0.5413, -0.6185,
            1.1391],
          [ 0.2312,  0.3316,  0.4868, -1.2263, -0.2973, -0.9294,  1.1159,
            1.6440]],

         [[ 0.5560,  0.7075, -1.6191,  0.2663, -1.5125,  1.4900,  0.2657,
           -0.1849],
          [ 0.7743, -1.7380, -1.2998,  0.8160, -0.8393, -0.2413,  0.1021,
            0.8224],
          [-0.0560, -0.2023,  0.5151,  0.7342,  1.3579, -0.1491,  0.8157,
            0.8372],
          [ 0.8885, -1.2640, -0.6817, -0.5922,  0.3488, -1.4064,  0.2926,
            0.8435]]],


        [[[ 1.3950, -0.3206,  1.0995,  0.8106, -0.6397,  0.6

Разница между batch и tensor сосотит в том, что batch состоит из тензоров, а его размер говорит о количестве тензоров в нем