In [1]:
%matplotlib inline

# Зайцев Н. ПИ20-1В


Введение в PyTorch
================

Это основанный на Python научный вычислительный пакет, ориентированный на два набора аудиторий:

* замена NumPy для использования мощности графических процессоров
* исследовательская платформа глубокого обучения которая обеспечивает максимальную гибкость и скорость

Начало
---------------

Тензоры

^^^^^^^

Тензоры похожи на ndarrays библиотеки numpy, с добавлением того, что
Тензоры также могут быть использованы на графическом процессоре для ускорения вычислений.



In [2]:
from __future__ import print_function
import torch
print(torch.cuda.is_available())

False


#### Примечание
Неинициализированная тензор объявляется, но не содержит определенных известных значений до ее использования. Когда создается неинициализированная матрица, все значения, которые были в выделенной памяти в то время, будут отображаться как начальные значения.



Создадим неинициализированный тензор 5x3:



In [3]:
x = torch.empty(5, 3)
print(x)
type(x)

tensor([[1.1210e-44, -0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.5873e-43, 3.6013e-43],
        [3.5873e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.1704e-41, 0.0000e+00]])


torch.Tensor

Создадим тензор со случайным набором:

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1135, 0.4995, 0.0702],
        [0.7641, 0.5913, 0.0776],
        [0.7805, 0.1992, 0.7391],
        [0.9702, 0.6763, 0.8789],
        [0.5432, 0.6016, 0.5175]])


Создадим тензор заполненный 0 типа long:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Создадим тензор из списка и изменим его тип:





In [6]:
x = torch.tensor([5.5, 3])
print(x)
x.type(torch.int)

tensor([5.5000, 3.0000])


tensor([5, 3], dtype=torch.int32)


или создадим тензор на основе существующего тензора. Эти методы будут повторно использовать свойства входного тензора, например тип, если только пользователь не предоставит новые значения

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* метод применяется для размера
print(x)

x = torch.randn_like(x, dtype=torch.float64)    #  dtype позволяет сменить тип!
print(x)                                      

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3020, -0.2309, -0.9435],
        [ 0.5069, -0.1378,  0.3055],
        [-0.2309, -0.7468,  0.9562],
        [ 1.0634, -0.7753, -0.4065],
        [ 0.9596, -1.1341, -0.2818]], dtype=torch.float64)


Получим размер тензора:



In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
x1 = torch.tensor([[1, 2], [3, 4]])
y=torch.unsqueeze(x1,0)
print(y,y.size())
z=torch.unsqueeze(x1,-1)
print(z,z.size())
t=torch.unsqueeze(x1,1)
print(t,t.size())

tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2])
tensor([[[1],
         [2]],

        [[3],
         [4]]]) torch.Size([2, 2, 1])
tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])


#### Примечание
`torch.Size` это кортеж и поддерживает все операции для кортежей

Операции

^^^^^^^^^^

Существует несколько синтаксисов для операций. В следующем
примере мы рассмотрим операцию сложения.

Сложение: синтаксис 1-й



In [10]:
y = torch.rand(5, 3)
print(x,'\n',y)
print(x + y)

tensor([[ 0.3020, -0.2309, -0.9435],
        [ 0.5069, -0.1378,  0.3055],
        [-0.2309, -0.7468,  0.9562],
        [ 1.0634, -0.7753, -0.4065],
        [ 0.9596, -1.1341, -0.2818]], dtype=torch.float64) 
 tensor([[0.3494, 0.4717, 0.0199],
        [0.2307, 0.9280, 0.3101],
        [0.8412, 0.4676, 0.8158],
        [0.0800, 0.2668, 0.7542],
        [0.9447, 0.9651, 0.1343]])
tensor([[ 0.6514,  0.2408, -0.9236],
        [ 0.7376,  0.7901,  0.6156],
        [ 0.6103, -0.2793,  1.7721],
        [ 1.1434, -0.5085,  0.3477],
        [ 1.9043, -0.1689, -0.1475]], dtype=torch.float64)


Сложение: синтаксис 2-й



In [11]:
print(torch.add(x, y))

tensor([[ 0.6514,  0.2408, -0.9236],
        [ 0.7376,  0.7901,  0.6156],
        [ 0.6103, -0.2793,  1.7721],
        [ 1.1434, -0.5085,  0.3477],
        [ 1.9043, -0.1689, -0.1475]], dtype=torch.float64)


Сложение: с выходным тензором в качестве аргумента



In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6514,  0.2408, -0.9236],
        [ 0.7376,  0.7901,  0.6156],
        [ 0.6103, -0.2793,  1.7721],
        [ 1.1434, -0.5085,  0.3477],
        [ 1.9043, -0.1689, -0.1475]])


Сложение: в одно действие (in-place)

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6514,  0.2408, -0.9236],
        [ 0.7376,  0.7901,  0.6156],
        [ 0.6103, -0.2793,  1.7721],
        [ 1.1434, -0.5085,  0.3477],
        [ 1.9043, -0.1689, -0.1475]])


#### Примечание

Любая операция, которая изменяет тензор в одно действие сопровождается ``_``. Например: ``x.copy_(y)``, ``x.t_()``, изменят ``x``.

Вы можете так же использовать стандартную NumPy-подобную индексацию со всеми ее особенностями!

In [14]:
print(x[:, 1])

tensor([-0.2309, -0.1378, -0.7468, -0.7753, -1.1341], dtype=torch.float64)


Изменение размера: Если вы хотите изменить размер/форму тензора, вы можете использовать ``torch.view``:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # размер -1 соответсвует остальным размерностям, т.е. 16/8=2 
print(x.size(), y.size(), z.size())
x,y

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


(tensor([[-0.1383, -0.5273,  0.0568,  0.7139],
         [ 1.2479,  0.7043, -0.0392, -0.0060],
         [-0.5788, -0.0869, -1.3352, -0.7599],
         [ 0.0536, -0.6426,  0.4445, -1.7039]]),
 tensor([-0.1383, -0.5273,  0.0568,  0.7139,  1.2479,  0.7043, -0.0392, -0.0060,
         -0.5788, -0.0869, -1.3352, -0.7599,  0.0536, -0.6426,  0.4445, -1.7039]))

Если у вас есть одноэлементный тензор, используйте `.item ()`, чтобы получить его значение

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0856])
0.08563277870416641


**Далее:**

100+ тензорные операции, в том числе транспонирование, индексирование, нарезка, математические операции, линейная алгебра, случайные числа и др описаны здесь: <https://pytorch.org/docs/torch>

Переход с NumPy
------------
Преобразование Torch Tensor в массив NumPy и наоборот-это легко.

Torch Tensor и массив NumPy будут совместно использовать свои базовые
ячейки памяти (если Torch Tensor находится на процессоре), и изменение одного изменит другое.

Преобразование Torch Tensor в массив NumPy

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


Посмотрим как массив NumPy изменяется в своих значениях.

In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Преобразование массива NumPy в Torch тензор

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Посмотрим как изменения nparray отразятся на тензоре 


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



Все тензоры на CPU за исключением CharTensor поддерживают преобразование в NumPy и обратно.

CUDA тензоры
------------

Тензоры могут быть перемещены на любой процессор методом ``.to``



In [21]:
# Данный код выполняется только, если доступен CUDA
# Для смены реализации тензора на и с GPU используется объект ``torch.device``
if torch.cuda.is_available():
    device = torch.device("cuda")          # это объект device типа CUDA  
    y = torch.ones_like(x, device=device)  # создает тензор на GPU
    x = x.to(device)                       # можно использовать ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # метод ``.to`` может также менять dtype!

Соединение тензоров
--------

Метод `torch.cat` соединяет тензоры вдоль заданного направления. Другой способ использовать `torch.stack`.

In [22]:
x=torch.ones(5)
y=x.add(1)
z=x.add(2)
t1 = torch.cat([x, y, z])
print(t1)

tensor([1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.])


In [23]:
t2=torch.vstack([x,y,z])
print(t2)

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.]])


In [24]:
t3=torch.hstack([x.view(-1,1),y.view(-1,1),z.view(-1,1)])
print(t3)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


Преобразование одноэлементных тензоров.
----
Рссмотрим одноэлементный тензор, полученный, например агрегацией всех элементов тензора в одно значение, его можно сразу же перевести в численное значение Python методом `item()`:

In [25]:
agg = x.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

5.0 <class 'float'>


Операции на месте
----
Операции, которые сохраняют значение вычисления в переменной которая участвовала в вычислениях называются операциями на месте. Они обозначаются суффиксом `_`. Например: `x.copy_(y)`, `x.t_()`, изменят `x`. 

Примечание: Операции на месте сохраняют немного памяти, но могут вызвать проблемы при вычислении производных потому, что мгновенно теряют предыдущее значение, поэтому использование их не поощеряется.


In [26]:
print(x, "\n")
x.add_(5)
print(x)

tensor([1., 1., 1., 1., 1.]) 

tensor([6., 6., 6., 6., 6.])


Матричные операции
---


## Задание 1.
Создать тензор размера 5 на 5, содержащий случайный набор числел в ячейках на диагонали и выше, ниже диагонали содержащий 0.


In [27]:
import torch

tensor = torch.triu(torch.rand((5, 5)))

print(tensor)

tensor([[0.8476, 0.3234, 0.8685, 0.0948, 0.9954],
        [0.0000, 0.3362, 0.1096, 0.1806, 0.3909],
        [0.0000, 0.0000, 0.2382, 0.0638, 0.0020],
        [0.0000, 0.0000, 0.0000, 0.9558, 0.6295],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.1092]])


## Задание 2.
Найти тезор обратный этому тензору.

In [28]:
inv_tensor = torch.inverse(tensor)
print(inv_tensor)

tensor([[ 1.1798e+00, -1.1351e+00, -3.7788e+00,  3.4968e-01, -8.6375e+00],
        [-0.0000e+00,  2.9747e+00, -1.3686e+00, -4.7062e-01, -7.9095e+00],
        [ 9.2788e-09, -1.7620e-08,  4.1978e+00, -2.8019e-01,  1.5396e+00],
        [-3.7071e-08,  5.8874e-08, -1.7457e-07,  1.0462e+00, -6.0303e+00],
        [ 2.2411e-08,  6.5338e-08, -5.6420e-08, -5.7179e-08,  9.1562e+00]])


Задание 3.
---
Сгенерируйте тензор случайных значений формы (10,10) с нормальным распределением значений со средним 2, и стандартным отклонением 3. Постройте матрицу парных расстояний между строками этой матрицы, найдите средние и стандартное отклонение нового тензора.

In [29]:
tensor = torch.randn(10, 10) * 3 + 2
distances = torch.cdist(tensor, tensor)

print("Отклонение: ", torch.mean(distances))
print("Стандартное отклонение: ", torch.std(distances))

Отклонение:  tensor(12.1278)
Стандартное отклонение:  tensor(5.3485)


Задание 4
---
Создайте тензор A, используя значения range(9). Разбить тензор на 3 одинаковых тензора a,b,c разбить тензор A на два тензора d, e, содержащие 5 и 4 значения из A, соединить тензоры d и e в обратном порядке. Составить из тензоров a, b, c тензор формы (3,3).

In [30]:
A_rng = range(9)
A = torch.tensor(A_rng)
print(A)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [31]:
a, b, c = torch.split(A, 3)
print(a)
print(b)
print(c)

tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])


In [32]:
d, e = torch.split(A, [5, 4])
print(d)
print(e)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8])


In [33]:
de = torch.cat((e, d), dim=0)
print(de)


tensor([5, 6, 7, 8, 0, 1, 2, 3, 4])


Задание 5
---
Проверить скорость выполнения матричного умножения на CPU и GPU. 

In [35]:
a = torch.randn(10000, 10000)
b = torch.randn(10000, 10000)

In [34]:
import time

start_time = time.time()
c = torch.matmul(a, b)
end_time = time.time()
execution_time_cpu = end_time - start_time

print("CPU time:", execution_time_cpu)

CPU time: 0.005700111389160156


### Cuda у меня не поддерживается

In [35]:
a_gpu = a.cuda()
b_gpu = b.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [38]:
start_time = time.time()
c_gpu = torch.matmul(a_gpu, b_gpu)
end_time = time.time()
time_gpu = end_time - start_time

print("GPU time:", time_gpu)

NameError: name 'a_gpu' is not defined